name: nasa_apod_viewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  flutter:
    sdk: flutter
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/NASA_logo.png
    - assets/California_Mendez_960.jpg
